---
# Will only download once
- name: Get VMD binaries
  get_url:
    url: "{{ vmd_download_link }}"
    dest: "{{ vmd_code_folder }}/{{  vmd_binary_archive }}"
  register: vmd_download

# For some reason this is not idempotent on travis
# See also https://github.com/ansible/ansible/issues/22254
# (but not sure it is related)
- name: Extract VMD binaries
  unarchive:
    src: "{{ vmd_code_folder}}/{{ vmd_binary_archive }}"
    dest: "{{ vmd_code_folder }}"
    remote_src: yes
  when: vmd_download.changed

- name: "Set $install_bin_dir in configure"
  lineinfile:
    path: "{{ vmd_topdir }}/configure"
    regexp: '^\$install_bin_dir="/usr/local/bin";$'
    line: '$install_bin_dir = "{{ vmd_install_dir}}/bin";'

- name: "Set $install_library_dir in configure"
  lineinfile:
    path: "{{ vmd_topdir }}/configure"
    regexp: '^\$install_library_dir="/usr/local/lib/\$install_name";$'
    line: '$install_library_dir = "{{ vmd_install_dir}}/lib/$install_name";'

- name: vmd - configure
  shell: ./configure
  args:
    chdir: "{{ vmd_topdir }}"
    #creates: "{{ vmd_topdir }}/Makefile"
  register: vmd_configure
  #when: vmd_download.changed

- name: vmd - make
  shell: make install
  args:
    chdir: "{{ vmd_topdir }}/src"
  register: vmd_make
  #when: vmd_configure.changed

- name: "Put a line in ${HOME}/.profile to add VMD binaries to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ vmd_install_dir }}/bin"

- name: "add desktop shortcut"
  template:
    src: vmd.desktop
    dest: "${HOME}/Desktop"
    mode: 0753
  when: not vmd_headless

- include_role:
    name: release_notes
  vars:
    section: "VMD"
    option: "version"
    value: "{{ vmd_version }}"
  when: release_notes is defined and release_notes

- include_role:
    name: release_notes
  vars:
    section: "VMD"
    option: "usage"
    value: >-
        VMD is installed in {{ vmd_topdir }}.
        'vmd' has been added to the PATH
  when: release_notes is defined and release_notes
